### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by pmcelhaney** [sgentle/caniuse-cmd#1]
It would be great to have a `~/.caniuse` file to specify my default options. For example, I'm generally interested in `--era e2`.

**Comment by jhonnymoreira** [comment]
@pmcelhaney it was one of the things that I thought today. I created an alias (since I'm using OS X) to deal with it, but a config file would be better.

**Comment by sgentle** [comment]
Good idea!

**Comment by pmcelhaney** [comment]
Thanks a lot. Just tested. It works great. Let me know if I can help with documenting the config file.

**Comment by sgentle** [comment]
Yeah absolutely! If you felt like adding something to the README it would be super helpful.
