### ISSUE TITLE
windows environment

### ISSUE THREAD

**Issue by myqianlan** [sgentle/caniuse-cmd#4]
like this:

T_T ...T_T..

![image](https://cloud.githubusercontent.com/assets/5117885/8976991/e7e2d148-36c6-11e5-9b31-02668a984c31.png)

**Comment by sgentle** [comment]
Hm, sorry to hear that. I was under the impression that recent versions of Windows have decent Unicode support, but I don't have a Windows machine to test. If you can find a set of characters that will display on Windows I'd be happy to add them!

I could possibly add a flag to use ascii-only symbols (Y/N/P for yes/no/partial)...

**Comment by MattiJarvinen-BA** [comment]
How mocha fixed this https://github.com/mochajs/mocha/pull/641

**Comment by AdrianoCahete** [comment]
:+1:

**Comment by sgentle** [comment]
I've merged @blindlybright's changes which should mitigate this, but if anyone would like to build on that to add symbols that appear in the default windows terminal fonts (as per @MattiJarvinen-BA's link) I'd be happy to accept pull requests!

**Comment by AdrianoCahete** [comment]
@myqianlan Try again with the latest code, please.

**Comment by myqianlan** [comment]
@AdrianoCahete haha, I use mac already...

**Comment by AdrianoCahete** [comment]
Oh... This is  horrible :P 

So, i belive we can close this issue @sgentle :)

**Comment by sgentle** [comment]
Oh well, I'm sure there are plenty of other windows users who will benefit from your efforts @AdrianoCahete. :)

**Comment by MattiJarvinen-BA** [comment]
Something fishy still with the partial support icon.

![image](https://cloud.githubusercontent.com/assets/12794435/13139927/c28c4eae-d637-11e5-8b44-a7259100fb00.png)

**Comment by AdrianoCahete** [comment]
@MattiJarvinen-BA  Which Windows version? Any edit/personalization in cmd?
